### ISSUE TITLE
FactionFriend Doesn't Load @ Login

### ISSUE THREAD

**Issue by Calesta** [fizzwidget/faction-friend#10]
Super excited to see the update so I installed it right away and upon logging in a bunch of my addons didn't load at startup.  All of them including FactionFriend said 'Only loadable on demand.'.  Disabled FactionFriend (the only new addition) and reloaded the UI and everything works as before.  Any ideas on why it would not load when I login and prevent other addons from loading as well?

**Comment by ShaunaGordon** [comment]
I'm unable to replicate this issue. Can you please try the following troubleshooting steps?

1. Ensure you downloaded the latest version of FactionFriend. The zip file should be named `gfw-factionfriend-7-0.zip`. The most likely cause is that you somehow didn't get the updated version. Any version of FactionFriend before 7.0 will not load in the current version of WoW.
1. Delete the FactionFriend folder and reinstall (and make sure you only have one folder and there's not another one nested inside the FactionFriend folder). If you had a previous version of FactionFriend and just unzipped it into your addons folder, it's possible something didn't get changed or copied like it was supposed to. A clean install should ensure you have 7.0 installed properly.
1. Turn off other addons and see if FactionFriend still says "only loadable on demand". It's possible that it's actually a different addon that's interfering with something in FactionFriend. To ensure that it is, indeed, FactionFriend that's failing, it should still fail when the other addons are disabled.

Going through these steps should uncover some more information for us to work with, but if they don't, we can get into some more involved troubleshooting methods.

**Comment by Calesta** [comment]
1.  Check.
2.  Check.
3.  Check.  Still says 'Only loadable on demand.'  Do I need to *do* something to get it to load?  There's no 'Load Addon' button that sometimes appears when you first enable a new addon from the 'Addon' button in the Game Menu.  Attached a screenshot (I think...)

![gfw_ff](https://cloud.githubusercontent.com/assets/13042214/17939672/ab4d4094-69f9-11e6-9ef8-936423a37db9.jpg)

**Comment by ShaunaGordon** [comment]
What happens if you uncheck `Load out of date addons`? Does FactionFriend still attempt to load?

**Comment by Calesta** [comment]
It loads when I turn off 'Load out of date addons'.

**Comment by ShaunaGordon** [comment]
Paste this into the chat window:

`/run print(LoadAddOn("GFWFactionFriend"))`

It should return two values, the first either "true" or "false", and the other either "nil" (if the first is "true") or other text (if the first is "false").

**Comment by fizzwidget** [comment]
Thanks @ShaunaGordon for the troubleshooting help.

Another thing to watch for might be that the addon folder name wants to be `GFW_FactionFriend`, but if you download the wrong zip from Github, or downloaded in the first day or two after I posted the 7.0 releases, it'll unzip with the wrong folder name.

**Comment by ShaunaGordon** [comment]
Anytime, Fizz. :)

And :+1: to the naming.

**Comment by Calesta** [comment]
Logged in today with 'Load out of date addons' checked.  FactionFriend appears to have loaded as I'm able to right-click the reputation bar and see the options there and I see a listing for it in the Addons section of the 'Interface' game menu.  This didn't happen the first time I tested and only loaded *after* unchecking the 'Load out of date addons'.  So I'm sort of puzzled.

Typed the message Shauna shared above (with it loaded and the box to load out of date addons checked) and it says...

false MISSING

Not sure what that means or how it helps, but now I'm really stumped how one day it worked one way and the next it worked another.  

Thanks again for the continued support.  I really appreciate it!

**Comment by Calesta** [comment]
I think it might be related to the following lines that are used to conditionally load it.  As I was adding addons one at a time and I activated 'Addon Loader', FactionFriend again didn't load and prevented other addons from loading.  

Here's what Addon Loader shows for FactionFriend:
X-LoadOn-Hooks: ReputationWatchBar_Update
X-LoadOn-ReputationWatchBar_Update: LoadAddOn('GFW_FactionFriend')

Perhaps there's been changes for 7.0+ that make these obselete or in need of a change?  

I found this comment when using Google to search for 'ReputationWatchBar_Update'.

-- begin quote
In legion ReputationWatchBar_Update was removed

at line 74 you have this:

hooksecurefunc("ReputationWatchBar_Update", function()
    if not PitBull4_ReputationBar:IsEnabled() then
        return
    end
    for frame in PitBull4:IterateFramesForUnitID("player") do
        PitBull4_ReputationBar:Update(frame)
    end
end)

This is removing calling the reputation bar

However, simply changing to this restores functionality

ReputationFrame_Update
--end quote

**Comment by fizzwidget** [comment]
`ReputationWatchBar_Update` went away, but `ReputationFrame_Update` isn't the right function to hook for the functionality we want (even if it does make errors go away for now). But I know how to fix it now, thanks for the diagnosis... and keep an eye out for a new release soonish.

**Comment by ShaunaGordon** [comment]
PitBull4 isn't part of FactionFriend, and looks like what might have been the issue. According to Curse, it looks like it just got updated on the 18th, so might be what had been causing the issue, and why it worked when load out of date addons was off. Do you know if you downloaded other updates since last Thursday?

@fizzwidget -- FactionFriend's only reference to ReputationWatchBar is the FFF function of that name, which wraps the actual functionality. We do use the new `ReputationWatchBar.OverlayFrame.Text:SetText` syntax. Neither `reputationwatchframe_update` nor `reputationframe_update` are used in FactionFriend's 7.0 code that I've found.

**Comment by Calesta** [comment]
@ShaunaGordon The PitBull4 code was for reference only, I don't use the addon.  I was trying to make the point that 'ReputationWatchBar_Update' had been deprecated.

@fizzwidget Thanks!  Appreciate the quick response!

**Comment by fizzwidget** [comment]
This should be fixed now — either wait for the proper 7.0.1 release and test against that or download the current sources off master.

**Comment by Calesta** [comment]
Uhoh... I think I messed something up looking for the 7.0.1 version.  I clicked fork looking for it and it added something for me.  Can you delete it?!?  Sorry!

**Comment by ShaunaGordon** [comment]
Clicking fork doesn't add anything to the master repository. It simply creates a copy of it for you to play around with with. You can delete your fork by going to it in your own "repositories" listing (it will show as "calesta/factionfriend" as opposed to "fizzwidget/factionfriend") and going to the Settings tab. At the bottom, there is a delete button. Don't worry, it will only delete your fork. Alternatively, you can leave it there, as it's not hurting anything.

**Comment by Calesta** [comment]
Thanks @ShaunaGordon!  Done.  I was worried I might have messed something up.
