### ISSUE TITLE
Tokens timewalking are missing

### ISSUE THREAD

**Issue by milotic** [fizzwidget/faction-friend#11]
Hi, in 6.2 all old tokens of rep and new tokens back via timewalking

new currency is http://www.wowhead.com/currency=1166/timewarped-badge

**Comment by ShaunaGordon** [comment]
Technically speaking, the badges, themselves, are not reputation items (ie - they don't represent a gain in reputation on their own, like the [Medallion of the Legion](http://www.wowhead.com/item=128315/medallion-of-the-legion), for example). However, it does appear that they can be used to buy [commendations for the old factions](http://www.wowhead.com/currency=1166/timewarped-badge#items:50+14-2-17+1).

After some digging, it appears Timewalking is going to be a recurring event (as opposed to a one-time event, like the pre-patch events or the opening of AQ), so it's definitely going to be worthwhile to add these in.

@fizzwidget I don't suppose there's a more efficient way to detect and store reputation gain items than the current way we do this? Perhaps even a sort of development tool that would allow us to gather that information to be included in the addon?

**Comment by fizzwidget** [comment]
Merged #12 and expanded it to reuse the code I had for showing rep gained from justice points -> commendations conversion, so you can now see time warped badge -> commendation -> rep gains.

@ShaunaGordon Sadly, the addon API doesn't provide that level of introspection for items. There might be some value in an external tool that could scrape reputation gain info from Wowhead, but that's a hairy problem itself, and not my strong suit. Luckily new rep gain avenues (of the sort FF is designed to track) come along infrequently enough that a handcrafted list remains pretty feasible.
