### ISSUE TITLE
Add Medallion of the Legion to item list

### ISSUE THREAD

**Issue by ShaunaGordon** [fizzwidget/faction-friend#14]
[Medallion of the Legion](http://www.wowhead.com/item=128315/medallion-of-the-legion) adds 1000 reputation to all of the Draenor factions. Is there a better way to go about adding this item than just listing each faction and adding the item in the ItemInfo dictionary?

**Comment by fizzwidget** [comment]
Not really—the data model is faction-centric, with a tree expanding to items, and it'd be a big rearchitecting to make it the other way around. But it's an easy copy/paste job.
