### ISSUE TITLE
FactionFriend 7.0.1 - Not Loading at Login

### ISSUE THREAD

**Issue by Calesta** [fizzwidget/faction-friend#15]
The good news => the changes you made to 'hook the right reputation bar func' seemed to allow my other addons to load as they normally would with FactionFriend enabled.

The bad news => FactionFriend still isn't loading.  I'm unable to right-click on my reputation bar to see the context menu, nor am I able to see it in the list of addons.  I'm going to go through the same troubleshooting used that Shauna originally posted to see if I can isolate if it's the addon or some sort of co-existence issue.

**Comment by Calesta** [comment]
When I remove AddonLoader completely from the 'Addons' folder then FactionFriend loads.  I suppose I could *not* use AddonLoader, but it does provide some functionality that I'd rather keep and there are lots of my addons that can benefit from it.

X-LoadOn-Hooks: MainMenuBar_UpdateExperienceBars

When I add this as a custom condition for FactionFriend in the AddonLoader options and reload, it works.

X-LoadOn-Always: delayed

I'm guessing that 'MainMenuBar_UpdateExperienceBars' is either the wrong load condition or is incomplete?  Hope this helps!

**Comment by fizzwidget** [comment]
On second thought, AddonLoader support is sort of superfluous to FF — to do anything with the reputation watch bar we're pretty much loading right after login anyway. Just killing it seems more sensible at this point.
