### ISSUE TITLE
Artifact Power bar doesn't play nice

### ISSUE THREAD

**Issue by Tuhljin** [fizzwidget/faction-friend#19]
When you equip your class artifact in Legion, the Reputation bar is replaced by an Artifact Power bar. I'm not sure what the best way to go about it is, but I'd definitely like to see FF make it friendlier.

Perhaps you could simply make it so right-clicking on the Artifact Power bar opens the right-click menu FF adds to the Reputation Bar, and there could be an option at the bottom of that menu for Artifact Power so you can easily swap between a reputation and artifact power. Or maybe you could even show both bars at once. Even better, both ways could be implemented but the player chooses between them.

**Comment by ShaunaGordon** [comment]
I was thinking about this, too, as I noticed the same thing. Blizzard's decision to add a third bar, without actually adding a third bar (at least not by default) screws with stuff. 

The good news is that it's really only an issue (at least prior to 7.1, my main computer is down at the moment, so I haven't tested it with the latest patch) before you hit 110. Once you hit 110, the experience bar is dropped out, the artifact power bar moves to the position of "primary" bar, and the faction bar returns to its usual "secondary" bar position (as you'd see it prior to getting your artifact weapon), and happy days are here again.

Of course, that still leaves the issues of a) AP vs faction as primary, and b) the three-bar dilemma in 100-109.

Depending on how much of a pain it is to code up, we could offer three options:

1. Show all three bars (duplicate the secondary bar UI and stack it on top of the secondary bar; this assumes we can shift the other UI elements to account for the extra space). -- more involved initially on the UI front, but doesn't need any settings or anything like that, and hope the AP thing isn't a one-off
1. Don't show faction, only AP and XP (current default behavior, at least more or less) -- no work required, but user loses usefulness of FF for a not-insignificant period of time
1. Show Faction and either AP or XP (this would probably be two options, in practice, but it's the same thing, conceptually) -- more work in settings and to get the bars displaying properly (as well as a can of worms regarding combinations and which is primary vs secondary bar), but keeps the UI the same (no shifting of other elements necessary, no creating an additional bar, just need to take over the segment that determines what goes in which bar)

Just spitballing, but the "should faction be primary" issue could be resolved with a checkbox "faction as primary bar," which could be used for any of the above, and make faction the main one, and the others the secondary/tertiary ones, regardless of the other options.

**Comment by Tuhljin** [comment]
Don't forget what I suggested before:

4. Show XP and either AP or Faction, treating AP as a pseudo-faction -- that is, until XP is no longer relevant and we get AP and Faction at the same time as is apparently the norm at 110. You could have Artifact Power as an option on the right-click menu FF adds to the Reputation bar and also add that menu to the Artifact Power bar, letting you switch from AP to any faction and vice versa.

I think this would be easier to implement than the others, and it's pretty intuitive, as well.

Bonus points if there's an option to automatically switch to AP when it detects you gained artifact power, similar to the switch when you gain faction points. More bonus points if your class order hall can optionally make an automatic switch to AP, as well.

**Comment by Tuhljin** [comment]
One thing to keep in mind is that although I said the Artifact Power bar replaces the Reputation bar, you can, without needing any addons, switch it back to Reputation by checking the "Show as Experience Bar" box for any faction in the Reputation panel. You switch back to AP by unchecking the box. This is why I think my suggested option wouldn't be too difficult to implement.

**Comment by ShaunaGordon** [comment]
Oh! I see what you're saying now. So it would switch to AP when you use an item (and, as an added bonus, the "potential gains" meter could be added, too; only concern there, above and beyond the bar functionality itself, is artifact knowledge level for dealing with the calculations), like it would for faction-gaining items. I misunderstood that before.

I'll have to play around with the bars with and without FF installed to see what the behavior is that's there, and make note of what my personal settings are, at least to provide myself with some context. I know I have faction and AP at the same time on my 110, which does the primary/secondary bar thing similar to sub-100 XP/faction display. I'm curious to see for myself exactly how that behaves on my 100s characters.

One of the biggest issues I see with giving it the faction treatment is the sheer number of levels and the potentials of coloring it, based on my understanding of how the current bars work in FF (it might not support doing that and might try to color it, or just break entirely). I could be missing something, though.

**Comment by fizzwidget** [comment]
Much belated followup: now it's 8.0, and all the AP got sucked away into Sargeras' sword or something, so we don't have an AP bar anymore. But soon the Battle for Azeroth gets going and we have an Azerite bar instead, so we're back to wanting to show up to three bars (XP while leveling, faction, and "whatever the current expansion's MacGuffin is") but only being able to show two.

It looks like there might be some infrastructure one could build on in Blizzard's StatusTrackingBarManager to get three bars showing, but I don't really have the time to experiment. (Anyone who does is welcome to open a PR, though!) 

Until then, the plan for FF will be to just continue augmenting the reputation bar whenever/wherever it shows.
