### ISSUE TITLE
missing pandaria tokens in 7.1.0 and new tokens to 7.1.5

### ISSUE THREAD

**Issue by milotic** [fizzwidget/faction-friend#20]
hi, other tokens 

first pack: http://www.wowhead.com/npc=69769/zandalari-warbringer
and in prt add new tokens to patch 7.1.5 http://www.icy-veins.com/forums/topic/25934-patch-715-mists-of-pandaria-timewalking/

**Comment by fizzwidget** [comment]
Thanks for the ~~feebas~~ feedback! All of these are added in release 7.2.
