### ISSUE TITLE
7.2 Paragon Rep (Exact error message)

### ISSUE THREAD

**Issue by Kyrgune** [fizzwidget/faction-friend#22]
Message: ..\AddOns\GFW_FactionFriend\FactionFriend.lua line 219:
   attempt to compare number with nil
Debug:
   GFW_FactionFriend\FactionFriend.lua:219: filterFunc()

**Comment by MuffinManKen** [comment]
The new rep gain no longer gives an amount earned, so the amount is nil. A quick hack to get rid of the error is to add this to the end of FFF_FactionInfoFromMessage

    if (factionName == nil) then
            if (FFF_FACTION_STANDING_INCREASED_GENERIC == nil) then
                FFF_FACTION_STANDING_INCREASED_GENERIC = GFWUtils.FormatToPattern(FACTION_STANDING_INCREASED_GENERIC);
            end
            _, _, factionName = string.find(message, FFF_FACTION_STANDING_INCREASED_GENERIC);
            if (factionName) then
                amount = 1; --A dummy value so something can be returned
            end
        end

**Comment by cristamd** [comment]
I submitted #23 with the change @MuffinManKen suggested above after verifying that it works on my machine.

**Comment by fizzwidget** [comment]
Included this and other Paragon related changes in release 7.2. Thanks!
