### ISSUE TITLE
[BfA Beta] Any Plans to Update for Battle for Azeroth?

### ISSUE THREAD

**Issue by Calesta** [fizzwidget/faction-friend#28]
I tried using this amazing add-on in the BfA Beta and Blizzard's changed some of the bars so it doesn't seem to work and throws LUA errors.

Just curious if you and your helpers are planning on updating this for the launch of the expansion.  I haven't seen a lot of activity on http://fizzwidget.com/ so I'm not sure if you're still actively playing / updating your addons.

Hope you're well and that you'll consider fixing it. :)

P.S.  Scrollmaker works just fine. :)

**Comment by Enigma-TL** [comment]
Would also like to know this. Been using it since it came out and love it.

**Comment by gregormoody** [comment]
Just writing to let you know that I also appreciate this addon and looking forward to its  update

**Comment by fizzwidget** [comment]
Current code in the repo as of 375524f should work with 8.0 / BfA. Anyone watching this is welcome to test — I'm gonna let it bake a bit before pushing it live as on official release.

**Comment by Enigma-TL** [comment]
Just got the code will test it today when BfA goes live.

On Sun, Aug 12, 2018 at 2:56 AM, Gazmik Fizzwidget <notifications@github.com
