### ISSUE TITLE
missing fishing "tokens" of legion

### ISSUE THREAD

**Issue by milotic** [fizzwidget/faction-friend#29]
http://es.wowhead.com/faction=2098 http://es.wowhead.com/item=146959/
http://es.wowhead.com/faction=2099 http://es.wowhead.com/item=146960/
http://es.wowhead.com/faction=2100 http://es.wowhead.com/item=146961
http://es.wowhead.com/faction=2101 http://es.wowhead.com/item=146962
http://es.wowhead.com/faction=2102 http://es.wowhead.com/item=146963
http://es.wowhead.com/faction=2097 http://es.wowhead.com/item=146848

**Comment by fizzwidget** [comment]
Duplicate of #27.
