### ISSUE TITLE
[Feature] Add Bodyguards to ignore list

### ISSUE THREAD

**Issue by ShaunaGordon** [fizzwidget/faction-friend#5]
We can gain reputation with bodyguards, but odds are good that most of the time we won't care much about it. It would be nice to have an option to not switch for the bodyguard, similar to how the "don't switch for guild" option works.

**Comment by ShaunaGordon** [comment]
Added a PR for this feature. Sections are added based on where they appear to make sense. Feel free to suggest tweaks or whatever.

**Comment by fizzwidget** [comment]
Merged PR #8
