### ISSUE TITLE
[Bug] Reputation Turn-In Prediction Marker Not Showing Consistently

### ISSUE THREAD

**Issue by ShaunaGordon** [fizzwidget/faction-friend#6]
In the process of testing the prediction for the Arakkoa Outcasts reputation gain item, I noticed that the little marker on the watch bar wasn't showing up. I wasn't sure if this was because it was a new one and I was missing something, or a larger bug. So, after farming the elites in Nagrand for enough relics to keep the Steamwheedle Preservation Society busy for the next six months (and subsequently getting enough leather to remodel the entirety of Thunder Bluff) to verify, I've found that this does, indeed, appear to be a bug:

![spsrep](https://cloud.githubusercontent.com/assets/579361/17838380/54e65d3c-679a-11e6-9d0c-0d6bb18fbce4.png)

![aorep](https://cloud.githubusercontent.com/assets/579361/17838381/564197f0-679a-11e6-919b-a937c3299ace.png)

Interestingly, when I went back to my garrison after getting enough relics to ensure I was past the text, the prediction marker appeared, and stayed when I switched between the Steamwheedle and Arakkoa.

However, a `/console reloadui` made it disappear again, and using my regular hearthstone (which takes me to the Shrine of Two Moons) did not make it appear, nor did reloading the UI. However, porting to Orgrimmar from the Shrine made it appear properly:

![spsrep2](https://cloud.githubusercontent.com/assets/579361/17838440/c5d6a3de-679b-11e6-8aeb-8ebb5a616e7a.png)

![aorep2](https://cloud.githubusercontent.com/assets/579361/17838442/c792f6f0-679b-11e6-8b98-aebece51072f.png)

I logged out and turned on BugGrabber/BugSack and the prediction bars were there on log in, but on a UI reload, it disappeared again. BugGrabber did not pick up any errors. :(

**Comment by fizzwidget** [comment]
Hmm.. I'll keep an eye out and see what I can do.

**Comment by fizzwidget** [comment]
ed41d00 might have fixed this.

**Comment by ShaunaGordon** [comment]
I was thinking the same thing, actually. I'll pull down that branch and toy with it to confirm.

**Comment by ShaunaGordon** [comment]
Looking good so far.
