### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Baltezar** [fizzwidget/faction-friend#9]

**Comment by fizzwidget** [comment]
The zip files had the wrong implicit folder name, so the addons don't come out as `GFW_DiggerAid`, `GFW_FactionFriend`, etc the way they're supposed to, which prevents them from loading. (That'll teach me to let Github make my zip files.) 

I just fixed the zip files on Github — sort of. You have to grab the "gfw-whatever-7-0.zip" on the Releases page, not the "source code" zip. Or if you re-download from www.wowinterface.com or www.fizwidget.com you'll get the right stuff now.
